### ISSUE TITLE
Update from version 1.2.1 to 2.0.3 -> tableView:cellForRowAtIndexPath: not call

### ISSUE THREAD

**Issue by TofPlay** [stefanoa/SASlideMenu#136]
Hi
My project worked originally with the version 1.2.1. I updated to the version 2.0.3. After that the tableView:cellForRowAtIndexPath: is never call on my class base on SASlideMenuViewController.

Any help will be appreciate

My config: iOS 8, Xcode 6.1.1

Tof

**Comment by stefanoa** [comment]
Can you provide a simple example that do not work?

**Comment by TofPlay** [comment]
Hi Stefanoa
I found the issu: on the storyboard my SASlideMenuRootViewController was defined as UINavigationController
